USE [TradingDB]
GO

/****** Object:  Table [dbo].[GOOGLE_HISTORY]    Script Date: 7/20/2017 12:37:38 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GOOGLE_HISTORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TICKER_SYMBOL] [nvarchar](20) NULL,
	[OPEN_PRICE] [money] NULL,
	[LOW_PRICE] [money] NULL,
	[HIGH_PRICE] [money] NULL,
	[CLOSE_PRICE] [money] NULL,
	[DATE_WITH_INTERVAL] [int] NULL,
 CONSTRAINT [PK_GOOGLE_HISTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[GOOGLE_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_GOOGLE_HISTORY_TICKER_SYMBOL_TICKER_DETAILS] FOREIGN KEY([TICKER_SYMBOL])
REFERENCES [dbo].[TICKER_DETAILS] ([TICKER_SYMBOL])
GO

ALTER TABLE [dbo].[GOOGLE_HISTORY] CHECK CONSTRAINT [FK_GOOGLE_HISTORY_TICKER_SYMBOL_TICKER_DETAILS]
GO


