using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Trading.Model
{
    public class TickerList
    {
        public SortedDictionary<string, string> TickerCollection = new SortedDictionary<string, string>();
        private static List<string> ticker_lists = new List<string>();

        public static List<string> TickersList { get{ return ticker_lists; } set { ticker_lists = value; } }
        #region TickerKey


        private static string[] list_of_nse = {
            "3M India Ltd.","3MINDIA",
            "8K Miles Soft Services Ltd.","8KMILES",
            "ABB India Ltd.","ABB",
            "ACC Ltd.","ACC",
            "AIA Engineering Ltd.","AIAENG",
            "APL Apollo Tubes Ltd.","APLAPOLLO",
            "Aarti Industries Ltd.","AARTIIND",
            "Aban Offshore Ltd.","ABAN",
            "Adani Enterprises Ltd.","ADANIENT",
            "Adani Ports and Special Economic Zone Ltd.","ADANIPORTS",
            "Adani Power Ltd.","ADANIPOWER",
            "Adani Transmission Ltd.","ADANITRANS",
            "Aditya Birla Fashion and Retail Ltd.","ABFRL",
            "Advanced Enzyme Tech Ltd.","ADVENZYMES",
            "Aegis Logistics Ltd.","AEGISCHEM",
            "Ahluwalia Contracts (India) Ltd.","AHLUCONT",
            "Ajanta Pharmaceuticals Ltd.","AJANTPHARM",
            "Akzo Nobel India Ltd.","AKZOINDIA",
            "Alembic Pharmaceuticals Ltd.","APLLTD",
            "Alkem Laboratories Ltd.","ALKEM",
            "Allahabad Bank","ALBK",
            "Allcargo Logistics Ltd.","ALLCARGO",
            "Amara Raja Batteries Ltd.","AMARAJABAT",
            "Ambuja Cements Ltd.","AMBUJACEM",
            "Amtek Auto Ltd.","AMTEKAUTO",
            "Anant Raj Ltd.","ANANTRAJ",
            "Andhra Bank","ANDHRABANK",
            "Apar Industries Ltd.","APARINDS",
            "Apollo Hospitals Enterprises Ltd.","APOLLOHOSP",
            "Apollo Tyres Ltd.","APOLLOTYRE",
            "Arvind Ltd.","ARVIND",
            "Asahi India Glass Ltd.","ASAHIINDIA",
            "Ashok Leyland Ltd.","ASHOKLEY",
            "Ashoka Buildcon Ltd.","ASHOKA",
            "Asian Paints Ltd.","ASIANPAINT",
            //"AstraZenca Pharma India Ltd.","ASTRAZEN",
            //"Astral Poly Technik Ltd.","ASTRAL",
            //"Atul Ltd.","ATUL",
            //"Aurobindo Pharma Ltd.","AUROPHARMA",
            //"Avanti Feeds Ltd.","AVANTIFEED",
            //"Axis Bank Ltd.","AXISBANK",
            //"BASF India Ltd.","BASF",
            //"BEML Ltd.","BEML",
            //"BF Utilities Ltd.","BFUTILITIE",
            //"BGR Energy Systems Ltd","BGRENERGY",
            //"Bajaj Auto Ltd.","BAJAJ-AUTO",
            //"Bajaj Corp Ltd.","BAJAJCORP",
            //"Bajaj Electricals Ltd","BAJAJELEC",
            //"Bajaj Finance Ltd.","BAJFINANCE",
            //"Bajaj Finserv Ltd.","BAJAJFINSV",
            //"Bajaj Hindusthan Sugar Ltd.","BAJAJHIND",
            //"Bajaj Holdings & Investment Ltd.","BAJAJHLDNG",
            //"Balkrishna Industries Ltd.","BALKRISIND",
            //"Ballarpur Industries Ltd.","BALLARPUR",
            //"Balmer Lawrie & Co. Ltd.","BALMLAWRIE",
            //"Balrampur Chini Mills Ltd.","BALRAMCHIN",
            //"Bank of Baroda","BANKBARODA",
            //"Bank of India","BANKINDIA",
            //"Bata India Ltd.","BATAINDIA",
            //"Berger Paints India Ltd.","BERGEPAINT",
            //"Bharat Electronics Ltd.","BEL",
            //"Bharat Financial Inclusion Ltd.","BHARATFIN",
            //"Bharat Forge Ltd.","BHARATFORG",
            //"Bharat Heavy Electricals Ltd.","BHEL",
            //"Bharat Petroleum Corporation Ltd.","BPCL",
            //"Bharti Airtel Ltd.","BHARTIARTL",
            //"Bharti Infratel Ltd.","INFRATEL",
            //"Bhushan Steel Ltd.","BHUSANSTL",
            //"Biocon Ltd.","BIOCON",
            //"Birla Corporation Ltd.","BIRLACORPN",
            //"Bliss GVS Pharma Ltd.","BLISSGVS",
            //"Blue Dart Express Ltd.","BLUEDART",
            //"Blue Star Ltd.","BLUESTARCO",
            //"Bombay Burmah Trading Corporation Ltd.","BBTC",
            //"Bombay Dyeing & Manufacturing Co. Ltd.","BOMDYEING",
            //"Bosch Ltd.","BOSCHLTD",
            //"Britannia Industries Ltd.","BRITANNIA",
            //"CARE Ratings Ltd.","CARERATING",
            //"CCL Products (I) Ltd.","CCL",
            //"CESC Ltd.","CESC",
            //"CG Power and Industrial Solutions Ltd.","CGPOWER",
            //"CRISIL Ltd.","CRISIL",
            //"Cadila Healthcare Ltd.","CADILAHC",
            //"Can Fin Homes Ltd.","CANFINHOME",
            //"Canara Bank","CANBK",
            //"Capital First Ltd.","CAPF",
            //"Caplin Point Laboratories Ltd.","CAPLIPOINT",
            //"Carborundum Universal Ltd.","CARBORUNIV",
            //"Castrol India Ltd.","CASTROLIND",
            //"Ceat Ltd.","CEATLTD",
            //"Central Bank of India","CENTRALBK",
            //"Century Plyboards (India) Ltd.","CENTURYPLY",
            //"Century Textile & Industries Ltd.","CENTURYTEX",
            //"Cera Sanitaryware Ltd","CERA",
            //"Chambal Fertilizers & Chemicals Ltd.","CHAMBLFERT",
            //"Chennai Petroleum Corporation Ltd.","CHENNPETRO",
            //"Cholamandalam Investment and Finance Company Ltd.","CHOLAFIN",
            //"Cipla Ltd.","CIPLA",
            //"City Union Bank Ltd.","CUB",
            //"Coal India Ltd.","COALINDIA",
            //"Coffee Day Enterprises Ltd.","COFFEEDAY",
            //"Colgate Palmolive (India) Ltd.","COLPAL",
            //"Container Corporation of India Ltd.","CONCOR",
            //"Coromandel International Ltd.","COROMANDEL",
            //"Corporation Bank","CORPBANK",
            //"Crompton Greaves Consumer Electricals Ltd.","CROMPTON",
            //"Cummins India Ltd.","CUMMINSIND",
            //"Cyient Ltd.","CYIENT",
            //"D B Realty Ltd.","DBREALTY",
            //"D.B.Corp Ltd.","DBCORP",
            //"DCB Bank Ltd.","DCBBANK",
            //"DCM Shriram Ltd.","DCMSHRIRAM",
            //"DLF Ltd.","DLF",
            //"Dabur India Ltd.","DABUR",
            //"Dalmia Bharat Ltd.","DALMIABHA",
            //"Deepak Fertilisers & Petrochemicals Corp. Ltd.","DEEPAKFERT",
            //"Delta Corp Ltd.","DELTACORP",
            //"Den Networks Ltd.","DEN",
            //"Dena Bank","DENABANK",
            //"Dewan Housing Finance Corporation Ltd.","DHFL",
            //"Dhanuka Agritech Ltd.","DHANUKA",
            //"Dilip Buildcon Ltd.","DBL",
            //"Dish TV India Ltd.","DISHTV",
            //"Divi's Laboratories Ltd.","DIVISLAB",
            //"Dr. Lal Path Labs Ltd.","LALPATHLAB",
            //"Dr. Reddy's Laboratories Ltd.","DRREDDY",
            //"Dredging Corporation of India Ltd.","DREDGECORP",
            //"E.I.D. Parry (India) Ltd.","EIDPARRY",
            //"EIH Ltd.","EIHOTEL",
            //"Edelweiss Financial Services Ltd.","EDELWEISS",
            //"Eicher Motors Ltd.","EICHERMOT",
            //"Emami Ltd.","EMAMILTD",
            //"Endurance Technologies Ltd.","ENDURANCE",
            //"Engineers India Ltd.","ENGINERSIN",
            //"Equitas Holdings Ltd.","EQUITAS",
            //"Eros Intl Media Ltd.","EROSMEDIA",
            //"Escorts Ltd.","ESCORTS",
            //"Essel Propack Ltd.","ESSELPACK",
            //"Eveready Industries India Ltd.","EVEREADY",
            //"Exide Industries Ltd.","EXIDEIND",
            //"FDC Ltd.","FDC",
            //"Federal Bank Ltd.","FEDERALBNK",
            //"Federal-Mogul Goetze (India) Ltd.","FMGOETZE",
            //"Finolex Cables Ltd.","FINCABLES",
            //"Finolex Industries Ltd.","FINPIPE",
            //"Firstsource Solutions Ltd.","FSL",
            //"Fortis Healthcare Ltd.","FORTIS",
            //"Future Consumer Ltd.","FCONSUMER",
            //"Future Retail Ltd.","FRETAIL",
            //"GAIL (India) Ltd.","GAIL",
            //"GE Power India Ltd.","GEPIL",
            //"GHCL Ltd.","GHCL",
            //"GMR Infrastructure Ltd.","GMRINFRA",
            //"GVK Power & Infrastructures Ltd.","GVKPIL",
            //"Gateway Distriparks Ltd.","GDL",
            //"Gati Ltd.","GATI",
            //"Gayatri Projects Ltd.","GAYAPROJ",
            //"Gillette India Ltd.","GILLETTE",
            //"GlaxoSmithkline Consumer Healthcare Ltd.","GSKCONS",
            //"Glaxosmithkline Pharmaceuticals Ltd.","GLAXO",
            //"Glenmark Pharmaceuticals Ltd.","GLENMARK",
            //"Godfrey Phillips India Ltd.","GODFRYPHLP",
            //"Godrej Consumer Products Ltd.","GODREJCP",
            //"Godrej Industries Ltd.","GODREJIND",
            //"Godrej Properties Ltd.","GODREJPROP",
            //"Granules India Ltd.","GRANULES",
            //"Great Eastern Shipping Co. Ltd.","GESHIP",
            //"Greaves Cotton Ltd.","GREAVESCOT",
            //"Greenply Industries Ltd.","GREENPLY",
            //"Grindwell Norton Ltd.","GRINDWELL",
            //"Gruh Finance Ltd.","GRUH",
            //"Gujarat Alkalies & Chemicals Ltd.","GUJALKALI",
            //"Gujarat Fluorochemicals Ltd.","GUJFLUORO",
            //"Gujarat Gas Ltd.","GUJGASLTD",
            //"Gujarat Mineral Development Corporation Ltd.","GMDCLTD",
            //"Gujarat Narmada Valley Fertilizers and Chemicals Ltd.","GNFC",
            //"Gujarat Pipavav Port Ltd.","GPPL",
            //"Gujarat State Fertilizers & Chemicals Ltd.","GSFC",
            //"Gujarat State Petronet Ltd.","GSPL",
            //"Gulf Oil Lubricants India Ltd.","GULFOILLUB",
            //"HCL Infosystems Ltd.","HCL-INSYS",
            //"HCL Technologies Ltd.","HCLTECH",
            //"HDFC Bank Ltd.","HDFCBANK",
            //"HSIL Ltd.","HSIL",
            //"HT Media Ltd.","HTMEDIA",
            //"Hathway Cable & Datacom Ltd.","HATHWAY",
            //"Havells India Ltd.","HAVELLS",
            //"HeidelbergCement India Ltd.","HEIDELBERG",
            //"Hero MotoCorp Ltd.","HEROMOTOCO",
            //"Hexaware Technologies Ltd.","HEXAWARE",
            //"Himachal Fut Com Ltd.","HFCL",
            //"Himatsingka Seide Ltd.","HIMATSEIDE",
            //"Hindalco Industries Ltd.","HINDALCO",
            //"Hindustan Construction Co. Ltd.","HCC",
            //"Hindustan Copper Ltd.","HINDCOPPER",
            //"Hindustan Media Vent Ltd.","HMVL",
            //"Hindustan Petroleum Corporation Ltd.","HINDPETRO",
            //"Hindustan Unilever Ltd.","HINDUNILVR",
            //"Hindustan Zinc Ltd.","HINDZINC",
            //"Honeywell Automation India Ltd.","HONAUT",
            //"Housing Development Finance Corporation Ltd.","HDFC",
            //"Housing Development and Infrastructure Ltd.","HDIL",
            //"I T C Ltd.","ITC",
            //"ICICI Bank Ltd.","ICICIBANK",
            //"ICICI Prudential Life Insurance Company Ltd.","ICICIPRULI",
            //"ICRA Ltd.","ICRA",
            //"IDBI Bank Ltd.","IDBI",
            //"IDFC Bank Ltd.","IDFCBANK",
            //"IDFC Ltd.","IDFC",
            //"IFCI Ltd.","IFCI",
            //"IRB Infrastructure Developers Ltd.","IRB",
            //"ITD Cementation India Ltd.","ITDCEM",
            //"Idea Cellular Ltd.","IDEA",
            //"Igarashi Motors India Ltd.","IGARASHI",
            //"India Cements Ltd.","INDIACEM",
            //"Indiabulls Housing Finance Ltd.","IBULHSGFIN",
            //"Indiabulls Real Estate Ltd.","IBREALEST",
            //"Indian Bank","INDIANB",
            //"Indian Hotels Co. Ltd.","INDHOTEL",
            //"Indian Oil Corporation Ltd.","IOC",
            //"Indian Overseas Bank ","IOB",
            //"Indo Count Industries Ltd.","ICIL",
            //"Indoco Remedies Ltd.","INDOCO",
            //"Indraprastha Gas Ltd.","IGL",
            //"IndusInd Bank Ltd.","INDUSINDBK",
            //"Infibeam Incorporation Ltd.","INFIBEAM",
            //"Info Edge (India) Ltd.","NAUKRI",
            //"Infosys Ltd.","INFY",
            //"Inox Leisure Ltd.","INOXLEISUR",
            //"Inox Wind Ltd.","INOXWIND",
            //"Intellect Design Arena Ltd.","INTELLECT",
            //"InterGlobe Aviation Ltd.","INDIGO",
            //"Ipca Laboratories Ltd.","IPCALAB",
            //"J.B. Chemicals & Pharmaceuticals Ltd.","JBCHEPHARM",
            //"J.K. Cement Ltd.","JKCEMENT",
            //"J.Kumar Infraprojects Ltd.","JKIL",
            //"JBF Industries Ltd.","JBFIND",
            //"JK Lakshmi Cement Ltd.","JKLAKSHMI",
            //"JK Tyre & Industries Ltd.","JKTYRE",
            //"JM Financial Ltd.","JMFINANCIL",
            //"JMT Auto Ltd.","JMTAUTOLTD",
            //"JSW Energy Ltd.","JSWENERGY",
            //"JSW Steel Ltd.","JSWSTEEL",
            //"Jagran Prakashan Ltd.","JAGRAN",
            //"Jai Corp Ltd.","JAICORPLTD",
            //"Jain Irrigation Systems Ltd.","JISLJALEQS",
            //"Jaiprakash Associates Ltd.","JPASSOCIAT",
            //"Jet Airways (India) Ltd.","JETAIRWAYS",
            //"Jindal Poly Films Ltd.","JINDALPOLY",
            //"Jindal Steel & Power Ltd.","JINDALSTEL",
            //"Johnson Controls - Hitachi Air Conditioning India Ltd.","JCHAC",
            //"Jubilant Foodworks Ltd.","JUBLFOOD",
            //"Jubilant Life Sciences Ltd.","JUBILANT",
            //"Justdial Ltd.","JUSTDIAL",
            //"Jyothy Laboratories Ltd.","JYOTHYLAB",
            //"K.P.R. Mill Ltd.","KPRMILL",
            //"KNR Constructions Ltd.","KNRCON",
            //"KPIT Technologies Ltd.","KPIT",
            //"KRBL Ltd.","KRBL",
            //"Kajaria Ceramics Ltd.","KAJARIACER",
            //"Kalpataru Power Transmission Ltd.","KALPATPOWR",
            //"Kansai Nerolac Paints Ltd.","KANSAINER",
            //"Karnataka Bank Ltd.","KTKBANK",
            //"Karur Vysya Bank Ltd.","KARURVYSYA",
            //"Kaveri Seed Company Ltd.","KSCL",
            //"Kec International Ltd.","KEC",
            //"Kesoram Industries Ltd.","KESORAMIND",
            //"Kitex Garments Ltd.","KITEX",
            //"Kolte-Patil Developers Ltd.","KOLTEPATIL",
            //"Kotak Mahindra Bank Ltd.","KOTAKBANK",
            //"Kwality Ltd.","KWALITY",
            //"L&T Technology Services Ltd.","LTTS",
            //"LIC Housing Finance Ltd.","LICHSGFIN",
            //"Lakshmi Machine Works Ltd.","LAXMIMACH",
            //"Lakshmi Vilas Bank Ltd.","LAKSHVILAS",
            //"Larsen & Toubro Infotech Ltd.","LTI",
            //"Larsen & Toubro Ltd.","LT",
            //"Laurus Labs Ltd.","LAURUSLABS",
            //"Lupin Ltd.","LUPIN",
            //"MMTC Ltd.","MMTC",
            //"MOIL Ltd.","MOIL",
            //"MRF Ltd.","MRF",
            //"Magma Fincorp Ltd.","MAGMA",
            //"Mahanagar Gas Ltd.","MGL",
            //"Mahanagar Telephone Nigam Ltd.","MTNL",
            //"Mahindra CIE Automotive Ltd.","MAHINDCIE",
            //"Mahindra Holidays & Resorts India Ltd.","MHRIL",
            //"Manappuram Finance Ltd.","MANAPPURAM",
            //"Mangalore Refinery & Petrochemicals Ltd.","MRPL",
            //"Manpasand Beverages Ltd.","MANPASAND",
            //"Marico Ltd.","MARICO",
            //"Marksans Pharma Ltd.","MARKSANS",
            //"Maruti Suzuki India Ltd.","MARUTI",
            //"Max Financial Services Ltd.","MFSL",
            //"Max India Ltd.","MAXINDIA",
            //"McLeod Russel India Ltd.","MCLEODRUSS",
            //"Merck Ltd.","MERCK",
            //"MindTree Ltd.","MINDTREE",
            //"Minda Corporation Ltd.","MINDACORP",
            //"Minda Industries Ltd.","MINDAIND",
            //"Monsanto India Ltd.","MONSANTO",
            //"Motherson Sumi Systems Ltd.","MOTHERSUMI",
            //"Motilal Oswal Financial Services Ltd.","MOTILALOFS",
            //"MphasiS Ltd.","MPHASIS",
            //"Muthoot Finance Ltd.","MUTHOOTFIN",
            //"NATCO Pharma Ltd.","NATCOPHARM",
            //"NBCC (India) Ltd.","NBCC",
            //"NCC Ltd.","NCC",
            //"NHPC Ltd.","NHPC",
            //"NIIT Technologies Ltd.","NIITTECH",
            //"NLC India Ltd.","NLCINDIA",
            //"NMDC Ltd.","NMDC",
            //"NTPC Ltd.","NTPC",
            //"Narayana Hrudayalaya Ltd.","NH",
            //"National Aluminium Co. Ltd.","NATIONALUM",
            //"Nava Bharat Ventures Ltd.","NBVENTURES",
            //"Navin Fluorine International Ltd.","NAVINFLUOR",
            //"Navkar Corporation Ltd.","NAVKARCORP",
            //"Navneet Education Ltd.","NAVNETEDUL",
            //"Network18 Media & Investments Ltd.","NETWORK18",
            //"Nilkamal Ltd.","NILKAMAL",
            //"Nitin Fire Protection Industries Ltd.","NITINFIRE",
            //"Oberoi Realty Ltd.","OBEROIRLTY",
            //"Oil & Natural Gas Corporation Ltd.","ONGC",
            //"Oil India Ltd.","OIL",
            //"Omaxe Ltd.","OMAXE",
            //"Oracle Financial Services Software Ltd.","OFSS",
            //"Orient Cement Ltd.","ORIENTCEM",
            //"Oriental Bank of Commerce","ORIENTBANK",
            //"Orissa Min Dev Co Ltd.","ORISSAMINE",
            //"PC Jeweller Ltd.","PCJEWELLER",
            //"PI Industries Ltd.","PIIND",
            //"PNB Housing Finance Ltd.","PNBHOUSING",
            //"PNC Infratech Ltd.","PNCINFRA",
            //"PTC India Fin Serv Ltd.","PFS",
            //"PTC India Ltd.","PTC",
            //"PVR Ltd.","PVR",
            //"Page Industries Ltd.","PAGEIND",
            //"Parag Milk Foods Ltd.","PARAGMILK",
            //"Persistent Systems Ltd.","PERSISTENT",
            //"Petronet LNG Ltd.","PETRONET",
            //"Pfizer Ltd.","PFIZER",
            //"Phoenix Mills Ltd.","PHOENIXLTD",
            //"Pidilite Industries Ltd.","PIDILITIND",
            //"Piramal Enterprises Ltd.","PEL",
            //"Polaris Consulting & Services Ltd.","POLARIS",
            //"Power Finance Corporation Ltd.","PFC",
            //"Power Grid Corporation of India Ltd.","POWERGRID",
            //"Praj Industries Ltd.","PRAJIND",
            //"Prestige Estates Projects Ltd.","PRESTIGE",
            //"Prism Cement Ltd.","PRISMCEM",
            //"Procter & Gamble Hygiene & Health Care Ltd.","PGHH",
            //"Punj Lloyd Ltd.","PUNJLLOYD",
            //"Punjab National Bank","PNB",
            //"Quess Corp Ltd.","QUESS",
            //"RBL Bank Ltd.","RBLBANK",
            //"Radico Khaitan Ltd","RADICO",
            //"Rain Industries Ltd","RAIN",
            //"Rajesh Exports Ltd.","RAJESHEXPO",
            //"Rallis India Ltd.","RALLIS",
            //"Ramco Systems Ltd.","RAMCOSYS",
            //"Ramkrishna Forgings Ltd.","RKFORGE",
            //"Rashtriya Chemicals & Fertilizers Ltd.","RCF",
            //"Ratnamani Metals & Tubes Ltd.","RATNAMANI",
            //"RattanIndia Power Ltd.","RTNPOWER",
            //"Raymond Ltd.","RAYMOND",
            //"Redington (India) Ltd.","REDINGTON",
            //"Relaxo Footwears Ltd.","RELAXO",
            //"Reliance Communications Ltd.","RCOM",
            //"Reliance Industrial Infrastructure Ltd.","RIIL",
            //"Reliance Industries Ltd.","RELIANCE",
            //"Reliance Infrastructure Ltd.","RELINFRA",
            //"Reliance Naval and Engineering Ltd.","RNAVAL",
            //"Reliance Power Ltd.","RPOWER",
            //"Religare Enterprises Ltd.","RELIGARE",
            //"Repco Home Finance Ltd.","REPCOHOME",
            //"Rolta India Ltd.","ROLTA",
            //"Ruchi Soya Industries Ltd.","RUCHISOYA",
            //"Rural Electrification Corporation Ltd.","RECLTD",
            //"S H Kelkar and Company Ltd.","SHK",
            //"SJVN Ltd.","SJVN",
            //"SKF India Ltd.","SKFINDIA",
            //"SML Isuzu Ltd.","SMLISUZU",
            //"SREI Infrastructure Finance Ltd.","SREINFRA",
            //"SRF Ltd.","SRF",
            //"Sadbhav Engineering Ltd.","SADBHAV",
            //"Sanofi India Ltd.","SANOFI",
            //"Schaeffler India Ltd.","SCHAEFFLER",
            //"Schneider Electric Infrastructure Ltd.","SCHNEIDER",
            //"Sharda Cropchem Ltd.","SHARDACROP",
            //"Sheela Foam Ltd.","SFL",
            //"Shilpa Medicare Ltd.","SHILPAMED",
            //"Shilpi Cable Tech Ltd.","SHILPI",
            //"Shipping Corporation of India Ltd.","SCI",
            //"Shree Cement Ltd.","SHREECEM",
            //"Shree Renuka Sugars Ltd.","RENUKA",
            //"Shriram City Union Finance Ltd.","SHRIRAMCIT",
            //"Shriram Transport Finance Co. Ltd.","SRTRANSFIN",
            //"Siemens Ltd.","SIEMENS",
            //"Snowman Logistics Ltd.","SNOWMAN",
            //"Sobha Ltd.","SOBHA",
            //"Solar Industries India Ltd.","SOLARINDS",
            //"Somany Ceramics Ltd.","SOMANYCERA",
            //"Sonata Software Ltd.","SONATSOFTW",
            //"South Indian Bank Ltd.","SOUTHBANK",
            //"State Bank of India","SBIN",
            //"State Trading Corporation of India Ltd.","STCINDIA",
            //"Steel Authority of India Ltd.","SAIL",
            //"Sterlite Technologies Ltd.","STRTECH",
            //"Strides Shasun Ltd.","STAR",
            //"Sudarshan Chemical Industries Ltd.","SUDARSCHEM",
            //"Sun Pharma Advanced Research Company Ltd.","SPARC",
            //"Sun Pharmaceutical Industries Ltd.","SUNPHARMA",
            //"Sun TV Network Ltd.","SUNTV",
            //"Sundaram Finance Ltd.","SUNDARMFIN",
            //"Sundram Fasteners Ltd.","SUNDRMFAST",
            //"Sunteck Realty Ltd.","SUNTECK",
            //"Supreme Industries Ltd.","SUPREMEIND",
            //"Suven Life Sciences Ltd.","SUVEN",
            //"Suzlon Energy Ltd.","SUZLON",
            //"Swan Energy Ltd.","SWANENERGY",
            //"Symphony Ltd.","SYMPHONY",
            //"Syndicate Bank","SYNDIBANK",
            //"Syngene International Ltd.","SYNGENE",
            //"TTK Prestige Ltd.","TTKPRESTIG",
            //"TV Today Network Ltd.","TVTODAY",
            //"TV18 Broadcast Ltd.","TV18BRDCST",
            //"TVS Motor Company Ltd.","TVSMOTOR",
            //"TVS Srichakra Ltd.","TVSSRICHAK",
            //"Take Solutions Ltd.","TAKE",
            //"Tamil Nadu Newsprint & Papers Ltd.","TNPL",
            //"Tata Chemicals Ltd.","TATACHEM",
            //"Tata Coffee Ltd.","TATACOFFEE",
            //"Tata Communications Ltd.","TATACOMM",
            //"Tata Consultancy Services Ltd.","TCS",
            //"Tata Elxsi Ltd.","TATAELXSI",
            //"Tata Global Beverages Ltd.","TATAGLOBAL",
            //"Tata Investment Corporation Ltd.","TATAINVEST",
            //"Tata Motors Ltd DVR","TATAMTRDVR",
            //"Tata Motors Ltd.","TATAMOTORS",
            //"Tata Power Co. Ltd.","TATAPOWER",
            //"Tata Sponge Iron Ltd.","TATASPONGE",
            //"Tata Steel Ltd.","TATASTEEL",
            //"Tech Mahindra Ltd.","TECHM",
            //"Techno Elt & Eng Co. Ltd.","TECHNO",
            //"Texmaco Rail & Eng. Ltd.","TEXRAIL",
            //"The Ramco Cements Ltd.","RAMCOCEM",
            //"Thermax Ltd.","THERMAX",
            //"Thomas Cook (India) Ltd.","THOMASCOOK",
            //"Thyrocare Technologies Ltd.","THYROCARE",
            //"Tide Water Oil (India) Ltd.","TIDEWATER",
            //"Timken India Ltd.","TIMKEN",
            //"Titan Company Ltd.","TITAN",
            //"Torrent Pharmaceuticals Ltd.","TORNTPHARM",
            //"Torrent Power Ltd.","TORNTPOWER",
            //"Trent Ltd.","TRENT",
            //"Trident Ltd.","TRIDENT",
            //"Triveni Turbine Ltd.","TRITURBINE",
            //"UCO Bank","UCOBANK",
            //"UFLEX Ltd.","UFLEX",
            //"UPL Ltd.","UPL",
            //"Ujjivan Financial Services Ltd.","UJJIVAN",
            //"UltraTech Cement Ltd.","ULTRACEMCO",
            //"Unichem Laboratories Ltd.","UNICHEMLAB",
            //"Union Bank of India","UNIONBANK",
            //"Unitech Ltd.","UNITECH",
            //"United Breweries Ltd.","UBL",
            //"V-Guard Industries Ltd.","VGUARD",
            //"V.I.P. Industries Ltd.","VIPIND",
            //"VRL Logistics Ltd.","VRLLOG",
            //"VST Industries Ltd.","VSTIND",
            //"Va Tech Wabag Ltd.","WABAG",
            //"Vakrangee Ltd.","VAKRANGEE",
            //"Vardhman Textiles Ltd.","VTL",
            //"Varun Beverages Ltd.","VBL",
            //"Vedanta Ltd.","VEDL",
            //"Videocon Industries Ltd.","VIDEOIND",
            //"Vijaya Bank","VIJAYABANK",
            //"Vinati Organics Ltd.","VINATIORGA",
            //"Voltas Ltd.","VOLTAS",
            //"WABCO India Ltd.","WABCOINDIA",
            //"Welspun Corp Ltd.","WELCORP",
            //"Welspun India Ltd.","WELSPUNIND",
            //"Whirlpool of India Ltd.","WHIRLPOOL",
            //"Wipro Ltd.","WIPRO",
            //"Wockhardt Ltd.","WOCKPHARMA",
            //"Wonderla Holidays Ltd.","WONDERLA",
            //"Yes Bank Ltd.","YESBANK",
            //"Zee Entertainment Enterprises Ltd.","ZEEL",
            //"Zee Learn Ltd.","ZEELEARN",
            //"Zensar Technolgies Ltd.","ZENSARTECH",
            //"Zydus Wellness Ltd.","ZYDUSWELL",
            //"eClerx Services Ltd.","ECLERX",
            //"Mahindra & Mahindra Financial Services Ltd.","M&MFIN",
            //"Mahindra & Mahindra Ltd.","M&M",
            //"Cox & Kings Ltd.","COX&KINGS",
            //"GE T&D India Ltd.","GET&D",
            //"IL&FS Transportation Networks Ltd.","IL&FSTRANS",
            //"Jammu & Kashmir Bank Ltd.","J&KBANK",
            //"L&T Finance Holdings Ltd.","L&TFH",
            //"United Spirits Ltd.","MCDOWELL-N",
        };
        #endregion

        static int Total_Stocks_to_Analyse = list_of_nse.Length;

        public static List<string> GetTickerList()
        {
            TickersList.Clear();
            for (int i = 0; i < Total_Stocks_to_Analyse; i=i+2 )
            {
               // i = i ++;
                TickersList.Add(list_of_nse[i+1].Trim());
            }

            return TickersList;
        }

        public TickerList()
        {
            for( int i = 0; i < Total_Stocks_to_Analyse;  )
            {
                TickerCollection.Add(list_of_nse[i++].Trim(), list_of_nse[i++].Trim());
            }
        }

        
    }
}
