USE [TradingDB]
GO

/****** Object:  StoredProcedure [dbo].[CreateGoogleHistory]    Script Date: 7/20/2017 12:38:54 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[CreateGoogleHistory]
	@TICKER_SYMBOL NVARCHAR(20),
	@OPEN_PRICE MONEY,
	@LOW_PRICE MONEY,
	@HIGH_PRICE MONEY,
	@CLOSE_PRICE MONEY,
	@DATE_WITH_INTERVAL INT
AS
BEGIN
	INSERT INTO GOOGLE_HISTORY
			(
				TICKER_SYMBOL,
				OPEN_PRICE,
				LOW_PRICE,
				HIGH_PRICE,
				CLOSE_PRICE,
				DATE_WITH_INTERVAL
			)
			VALUES
			(
				@TICKER_SYMBOL,
				@OPEN_PRICE,
				@LOW_PRICE,
				@HIGH_PRICE,
				@CLOSE_PRICE,
				@DATE_WITH_INTERVAL
			)
END

GO


