USE [TradingDB_Test]
GO

/****** Object:  Table [dbo].[EXCHANGE_DETAILS]    Script Date: 7/29/2017 2:48:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EXCHANGE_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GOOGLE_SECURITY_ID] [nvarchar](50) NULL,
	[EXCHANGE] [nvarchar](50) NULL,
	[LASTPRICE] [money] NULL,
	[PRICE] [money] NULL,
	[L_CUR] [money] NULL,
	[S] [int] NULL,
	[LAST_TRADE_TIME] [datetime] NULL,
	[LAST_TRDE_TIME_FORMATED] [nvarchar](50) NULL,
	[LAST_TRADE_DATETIME] [nvarchar](50) NULL,
	[CHANGE] [money] NULL,
	[C_FIX] [money] NULL,
	[CHANGE_PERCENTAGE] [money] NULL,
	[CP_FIX] [money] NULL,
	[CCOL] [nvarchar](50) NULL,
	[PCLS_FIX] [money] NULL,
	[AFTER_HOURS_LAST_PRICE] [money] NULL,
	[AFTER_HOURS_LAST_TRADE_TIMEFORMATED] [datetime] NULL,
	[GET_ACTUAL_RECORDTIME] [datetime] NULL,
	[CREATE_DATE] [datetime] NULL,
	[LAST_UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


