USE [TradingDB]
GO

/****** Object:  Table [dbo].[ORDER_HISTORY]    Script Date: 7/29/2017 9:06:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORDER_HISTORY](
	[ORDER_HISTORY_ID] [int] NOT NULL,
	[ORDER_MASTER_ID] [int] NULL,
	[ORDER_CODE_NAME] [nvarchar](50) NULL,
	[ORDER_TODAY_LEAST] [money] NULL,
	[ORDER_TODAY_MAXIM] [money] NULL,
	[ORDER_TODAY_MEAN] [money] NULL,
	[ORDER_BUYING_WINDOW_L] [money] NULL,
	[ORDER_BUYING_WINDOW_U] [money] NULL,
	[ORDER_HISTORY_LEAST] [money] NULL,
	[ORDER_HISTORY_MAX] [money] NULL,
	[ORDER_HISTORY_MEAN] [money] NULL,
	[ORDER_PURCHASED_AT] [money] NULL,
	[ORDER_STRATERGY] [money] NULL,
	[ORDER_QUANTITY] [int] NULL,
	[ORDER_STOP_LOSS] [money] NULL,
	[ORDER_BREAK_EVEN] [money] NULL,
	[ORDER_LPET] [money] NULL,
	[ORDER_PROFIT_TARGET] [money] NULL,
 CONSTRAINT [PK_ORDER_HISTORY] PRIMARY KEY CLUSTERED 
(
	[ORDER_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


