USE [TradingDB]
GO

/****** Object:  Table [dbo].[ORDER_MASTER]    Script Date: 7/29/2017 8:49:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORDER_MASTER](
	[ORDER_ID] [int] IDENTITY(1,1) NOT NULL,
	[TICKER_SYMBOL] [nvarchar](20) NULL,
	[LATEST_PRICE] [money] NULL,
	[DAY_GAIN] [money] NULL,
	[BOUGHT_PRICE] [money] NULL,
	[UNITS] [int] NULL,
	[PURCHACE_DATE] [datetime] NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ORDER_MASTER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_DETAILS_TICKER_DETAILS] FOREIGN KEY([TICKER_SYMBOL])
REFERENCES [dbo].[TICKER_DETAILS] ([TICKER_SYMBOL])
GO

ALTER TABLE [dbo].[ORDER_MASTER] CHECK CONSTRAINT [FK_ORDER_DETAILS_TICKER_DETAILS]
GO


