USE [master]
GO

/****** Object:  Database [TradingDB]    Script Date: 7/29/2017 3:01:06 PM ******/
DROP DATABASE [TradingDB]
GO

/****** Object:  Database [TradingDB]    Script Date: 7/29/2017 3:01:06 PM ******/
CREATE DATABASE [TradingDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TradingDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TradingDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TradingDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\TradingDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TradingDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TradingDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TradingDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TradingDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TradingDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TradingDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TradingDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TradingDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TradingDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TradingDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TradingDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TradingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TradingDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TradingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TradingDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TradingDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TradingDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TradingDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TradingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TradingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TradingDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TradingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TradingDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TradingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TradingDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TradingDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TradingDB] SET  MULTI_USER 
GO

ALTER DATABASE [TradingDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TradingDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TradingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TradingDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TradingDB] SET  READ_WRITE 
GO


